/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#include "enclave_curve_t.h"

#include <openenclave/edger8r/enclave.h>

#include <stdlib.h>
#include <string.h>
#include <wchar.h>

OE_EXTERNC_BEGIN

/**** ECALL functions. ****/

void ecall_enclave_SetCurveZMQ(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    enclave_SetCurveZMQ_args_t* pargs_in = (enclave_SetCurveZMQ_args_t*)input_buffer;
    enclave_SetCurveZMQ_args_t* pargs_out = (enclave_SetCurveZMQ_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    /* There were no in nor in-out parameters. */

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    /* There were no out nor in-out parameters. */

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    pargs_out->_retval = enclave_SetCurveZMQ(
        pargs_in->clientOrServer);

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ecall_enclave_ExportSealedPrivateKey(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    enclave_ExportSealedPrivateKey_args_t* pargs_in = (enclave_ExportSealedPrivateKey_args_t*)input_buffer;
    enclave_ExportSealedPrivateKey_args_t* pargs_out = (enclave_ExportSealedPrivateKey_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    /* There were no in nor in-out parameters. */

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->sealed_prikey)
        OE_SET_OUT_POINTER(sealed_prikey, sizeof(sealed_data_t*), sealed_data_t**);
    if (pargs_in->sealed_prikey_len)
        OE_SET_OUT_POINTER(sealed_prikey_len, sizeof(size_t), size_t*);
    if (pargs_in->pubkey)
        OE_SET_OUT_POINTER(pubkey, sizeof(uint8_t*), uint8_t**);
    if (pargs_in->pubkey_len)
        OE_SET_OUT_POINTER(pubkey_len, sizeof(size_t), size_t*);

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    pargs_out->_retval = enclave_ExportSealedPrivateKey(
        pargs_in->sealed_prikey,
        pargs_in->sealed_prikey_len,
        pargs_in->pubkey,
        pargs_in->pubkey_len);

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ecall_enclave_ImportSealedPrivateKey(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    enclave_ImportSealedPrivateKey_args_t* pargs_in = (enclave_ImportSealedPrivateKey_args_t*)input_buffer;
    enclave_ImportSealedPrivateKey_args_t* pargs_out = (enclave_ImportSealedPrivateKey_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    if (pargs_in->sealed_prikey)
        OE_SET_IN_POINTER(sealed_prikey, pargs_in->sealed_prikey_len, sealed_data_t*);
    if (pargs_in->pubkey)
        OE_SET_IN_POINTER(pubkey, pargs_in->pubkey_len, uint8_t*);

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    /* There were no out nor in-out parameters. */

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    pargs_out->_retval = enclave_ImportSealedPrivateKey(
        pargs_in->sealed_prikey,
        pargs_in->sealed_prikey_len,
        pargs_in->pubkey,
        pargs_in->pubkey_len);

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ecall_enclave_ImportServerPublicKey(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    enclave_ImportServerPublicKey_args_t* pargs_in = (enclave_ImportServerPublicKey_args_t*)input_buffer;
    enclave_ImportServerPublicKey_args_t* pargs_out = (enclave_ImportServerPublicKey_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    if (pargs_in->pubkey)
        OE_SET_IN_POINTER(pubkey, pargs_in->pubkey_len, uint8_t*);

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    /* There were no out nor in-out parameters. */

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    pargs_out->_retval = enclave_ImportServerPublicKey(
        pargs_in->pubkey,
        pargs_in->pubkey_len);

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ecall_enclave_ProduceHello(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    enclave_ProduceHello_args_t* pargs_in = (enclave_ProduceHello_args_t*)input_buffer;
    enclave_ProduceHello_args_t* pargs_out = (enclave_ProduceHello_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    /* There were no in nor in-out parameters. */

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->hello_msg)
        OE_SET_OUT_POINTER(hello_msg, sizeof(uint8_t*), uint8_t**);
    if (pargs_in->hello_msg_len)
        OE_SET_OUT_POINTER(hello_msg_len, sizeof(size_t), size_t*);

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    pargs_out->_retval = enclave_ProduceHello(
        pargs_in->hello_msg,
        pargs_in->hello_msg_len);

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ecall_enclave_ProcessHello(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    enclave_ProcessHello_args_t* pargs_in = (enclave_ProcessHello_args_t*)input_buffer;
    enclave_ProcessHello_args_t* pargs_out = (enclave_ProcessHello_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    if (pargs_in->hello_msg)
        OE_SET_IN_POINTER(hello_msg, pargs_in->hello_msg_len, uint8_t*);

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    /* There were no out nor in-out parameters. */

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    pargs_out->_retval = enclave_ProcessHello(
        pargs_in->hello_msg,
        pargs_in->hello_msg_len);

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ecall_enclave_ProduceWelcome(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    enclave_ProduceWelcome_args_t* pargs_in = (enclave_ProduceWelcome_args_t*)input_buffer;
    enclave_ProduceWelcome_args_t* pargs_out = (enclave_ProduceWelcome_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    /* There were no in nor in-out parameters. */

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->welcome_msg)
        OE_SET_OUT_POINTER(welcome_msg, sizeof(uint8_t*), uint8_t**);
    if (pargs_in->welcome_msg_len)
        OE_SET_OUT_POINTER(welcome_msg_len, sizeof(size_t), size_t*);

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    pargs_out->_retval = enclave_ProduceWelcome(
        pargs_in->welcome_msg,
        pargs_in->welcome_msg_len);

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ecall_enclave_ProcessWelcome(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    enclave_ProcessWelcome_args_t* pargs_in = (enclave_ProcessWelcome_args_t*)input_buffer;
    enclave_ProcessWelcome_args_t* pargs_out = (enclave_ProcessWelcome_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    if (pargs_in->welcome_msg)
        OE_SET_IN_POINTER(welcome_msg, pargs_in->welcome_msg_len, uint8_t*);

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    /* There were no out nor in-out parameters. */

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    pargs_out->_retval = enclave_ProcessWelcome(
        pargs_in->welcome_msg,
        pargs_in->welcome_msg_len);

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ecall_enclave_ProduceInitiate(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    enclave_ProduceInitiate_args_t* pargs_in = (enclave_ProduceInitiate_args_t*)input_buffer;
    enclave_ProduceInitiate_args_t* pargs_out = (enclave_ProduceInitiate_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    if (pargs_in->metadata_plaintext_)
        OE_SET_IN_POINTER(metadata_plaintext_, pargs_in->metadata_length, uint8_t*);

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->initiate_msg)
        OE_SET_OUT_POINTER(initiate_msg, sizeof(uint8_t*), uint8_t**);
    if (pargs_in->initiate_msg_len)
        OE_SET_OUT_POINTER(initiate_msg_len, sizeof(size_t), size_t*);

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    pargs_out->_retval = enclave_ProduceInitiate(
        pargs_in->metadata_plaintext_,
        pargs_in->metadata_length,
        pargs_in->initiate_msg,
        pargs_in->initiate_msg_len);

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ecall_enclave_ProcessInitiate(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    enclave_ProcessInitiate_args_t* pargs_in = (enclave_ProcessInitiate_args_t*)input_buffer;
    enclave_ProcessInitiate_args_t* pargs_out = (enclave_ProcessInitiate_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    if (pargs_in->initiate_msg)
        OE_SET_IN_POINTER(initiate_msg, pargs_in->initiate_msg_len, uint8_t*);

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->metadata_plaintext)
        OE_SET_OUT_POINTER(metadata_plaintext, sizeof(uint8_t*), uint8_t**);
    if (pargs_in->metadata_length)
        OE_SET_OUT_POINTER(metadata_length, sizeof(size_t), size_t*);

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    pargs_out->_retval = enclave_ProcessInitiate(
        pargs_in->initiate_msg,
        pargs_in->initiate_msg_len,
        pargs_in->metadata_plaintext,
        pargs_in->metadata_length);

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ecall_enclave_ProduceReady(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    enclave_ProduceReady_args_t* pargs_in = (enclave_ProduceReady_args_t*)input_buffer;
    enclave_ProduceReady_args_t* pargs_out = (enclave_ProduceReady_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    if (pargs_in->metadata_)
        OE_SET_IN_POINTER(metadata_, pargs_in->metadata_length, uint8_t*);

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->ready_msg)
        OE_SET_OUT_POINTER(ready_msg, sizeof(uint8_t*), uint8_t**);
    if (pargs_in->ready_msg_len)
        OE_SET_OUT_POINTER(ready_msg_len, sizeof(size_t), size_t*);

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    pargs_out->_retval = enclave_ProduceReady(
        pargs_in->metadata_,
        pargs_in->metadata_length,
        pargs_in->ready_msg,
        pargs_in->ready_msg_len);

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ecall_enclave_ProcessReady(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    enclave_ProcessReady_args_t* pargs_in = (enclave_ProcessReady_args_t*)input_buffer;
    enclave_ProcessReady_args_t* pargs_out = (enclave_ProcessReady_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    if (pargs_in->ready_msg)
        OE_SET_IN_POINTER(ready_msg, pargs_in->ready_msg_len, uint8_t*);

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->metadata_)
        OE_SET_OUT_POINTER(metadata_, sizeof(uint8_t*), uint8_t**);
    if (pargs_in->metadata_length)
        OE_SET_OUT_POINTER(metadata_length, sizeof(size_t), size_t*);

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    pargs_out->_retval = enclave_ProcessReady(
        pargs_in->ready_msg,
        pargs_in->ready_msg_len,
        pargs_in->metadata_,
        pargs_in->metadata_length);

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ecall_enclave_ProduceMessage(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    enclave_ProduceMessage_args_t* pargs_in = (enclave_ProduceMessage_args_t*)input_buffer;
    enclave_ProduceMessage_args_t* pargs_out = (enclave_ProduceMessage_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    if (pargs_in->msg)
        OE_SET_IN_POINTER(msg, pargs_in->msg_len, uint8_t*);

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->enc_msg)
        OE_SET_OUT_POINTER(enc_msg, sizeof(uint8_t*), uint8_t**);
    if (pargs_in->enc_msg_len)
        OE_SET_OUT_POINTER(enc_msg_len, sizeof(size_t), size_t*);

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    pargs_out->_retval = enclave_ProduceMessage(
        pargs_in->msg,
        pargs_in->msg_len,
        pargs_in->enc_msg,
        pargs_in->enc_msg_len);

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ecall_enclave_ProcessMessage(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    enclave_ProcessMessage_args_t* pargs_in = (enclave_ProcessMessage_args_t*)input_buffer;
    enclave_ProcessMessage_args_t* pargs_out = (enclave_ProcessMessage_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    if (pargs_in->enc_msg)
        OE_SET_IN_POINTER(enc_msg, pargs_in->enc_msg_len, uint8_t*);

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->msg)
        OE_SET_OUT_POINTER(msg, sizeof(uint8_t*), uint8_t**);
    if (pargs_in->msg_len)
        OE_SET_OUT_POINTER(msg_len, sizeof(size_t), size_t*);

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    pargs_out->_retval = enclave_ProcessMessage(
        pargs_in->enc_msg,
        pargs_in->enc_msg_len,
        pargs_in->msg,
        pargs_in->msg_len);

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

/**** ECALL function table. ****/

oe_ecall_func_t __oe_ecalls_table[] = {
    (oe_ecall_func_t) ecall_enclave_SetCurveZMQ,
    (oe_ecall_func_t) ecall_enclave_ExportSealedPrivateKey,
    (oe_ecall_func_t) ecall_enclave_ImportSealedPrivateKey,
    (oe_ecall_func_t) ecall_enclave_ImportServerPublicKey,
    (oe_ecall_func_t) ecall_enclave_ProduceHello,
    (oe_ecall_func_t) ecall_enclave_ProcessHello,
    (oe_ecall_func_t) ecall_enclave_ProduceWelcome,
    (oe_ecall_func_t) ecall_enclave_ProcessWelcome,
    (oe_ecall_func_t) ecall_enclave_ProduceInitiate,
    (oe_ecall_func_t) ecall_enclave_ProcessInitiate,
    (oe_ecall_func_t) ecall_enclave_ProduceReady,
    (oe_ecall_func_t) ecall_enclave_ProcessReady,
    (oe_ecall_func_t) ecall_enclave_ProduceMessage,
    (oe_ecall_func_t) ecall_enclave_ProcessMessage
};

size_t __oe_ecalls_table_size = OE_COUNTOF(__oe_ecalls_table);

/**** OCALL function wrappers. ****/

/* There were no ocalls. */
OE_EXTERNC_END
